# Generated by Django 5.1.4 on 2026-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotestimonial',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
