# Generated by Django 5.1.4 on 2026-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
