# Generated by Django 5.1.4 on 2026-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactsubmission_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='snapchat_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='website',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
