# Generated by Django 5.1.4 on 2026-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('billing_period', models.CharField(default='month', max_length=30)),
                ('best_for', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(blank=True, default=list)),
                ('suitable_projects', models.JSONField(blank=True, default=list)),
                ('task_hours', models.CharField(blank=True, max_length=100)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans_pricingplan',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
