# Generated by Django 5.1.4 on 2026-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_company',
            field=models.CharField(blank=True, default='Fusion5', max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_period',
            field=models.CharField(blank=True, default='Present', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, default='Remote · Available Worldwide', max_length=200),
        ),
    ]
