# Generated by Django 5.1.4 on 2026-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_avatar_url_teammember_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='preview_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
